### PR TITLE
Genre suggestions

### PR DESCRIPTION
**Pull request by iameru**
This is a wrapping component to have (later on) easily changeable suggestions for genres to the user.

this will be in Home.

### CODE REVIEW

**Comment by NoHara42** [comment]
This needs to be linked to an issue for me to review it

**Review by NoHara42 — CHANGES_REQUESTED** [review]
Please replace the chevron asset with inline imports from heroicons

**Comment by iameru** [comment]
this is not linked directly to an issue, rather its a component of the home page issue #20

**Comment by iameru** [comment]
used in #20

**Review by ReallyBoard123 — APPROVED** [review]
For me, in storybook, the "See all" part seems to be rendering in 2 lines, could you please check that once? Give me a thumbs up, if it hits okay in your system.

All good! This looks great

**Review by ReallyBoard123 — APPROVED** [review]

**Comment by iameru** [comment]
> For me, in storybook, the "See all" part seems to be rendering in 2 lines, could you please check that once? Give me a thumbs up, if it hits okay in your system.
> 
> All good! This looks great

for me this is happening too and I couldn't figure it out yet how to have it not break. Ill try more..

**Comment by iameru** [comment]
fixed the wrap in ee18bdc 
is this ready now?

**Review by ReallyBoard123 — APPROVED** [review]
You the boss!

**Review by NoHara42 — APPROVED** [review]

**Pull request merged**
